void o_matrix_normpdf(gsl_matrix *x, gsl_matrix *y, double z);
void o_matrix_invert(gsl_matrix *x, gsl_matrix *y);
void o_vector_add(gsl_vector *x, gsl_vector *y, gsl_vector *z);
void o_init_rng(gsl_rng *r);
void o_matrix_fwrite_col1(FILE *, gsl_matrix *);
void o_matrix_fwrite_char(FILE *, gsl_matrix *);
void o_matrix_fwrite(FILE *, gsl_matrix *);
void o_matrix_fread_char(FILE *, gsl_matrix *);
void o_matrix_fread(FILE *, gsl_matrix *);
double o_matrix_mean_row(gsl_matrix *,int);
double o_matrix_mean_col(gsl_matrix *,int);
double o_vector_mean(gsl_vector *);
double o_vector_sd(gsl_vector *);
void o_matrix_randn(gsl_rng *, double, double, gsl_matrix *);
void o_vector_randn(gsl_rng *, double, double, gsl_vector *);
void o_matrix_mean1(gsl_vector *, gsl_matrix *);
void o_matrix_mean2(gsl_vector *, gsl_matrix *);
void o_matrix_rep_cols(gsl_matrix *, gsl_vector *);
void o_matrix_rep_rows(gsl_matrix *, gsl_vector *);
void o_matrix_std1(gsl_vector *, gsl_matrix *);
double o_matrix_std_col(gsl_matrix *,int);
double o_vector_sum(gsl_vector *);
void o_vector_cumsum(gsl_vector *, gsl_vector *);
void o_randsample(gsl_rng *, gsl_vector *, gsl_vector *);
void o_matrix_replace_row(gsl_matrix *, int, gsl_matrix *, int);
typedef gsl_matrix gM;
typedef gsl_vector gV;
